# 2023-03-14

name: p02-gitleaks-03-$(Date:yyyyMMdd)$(Rev:.r)

pool:
  vmImage: ubuntu-latest  # same as ubuntu-20.04

resources:
  repositories:
    # - repository: templatesFortify
    #   type: git
    #   name: 'Common Cloud Services/fortify-03-template'
    #   ref: 'refs/heads/master'
    # TODO: we scan NOT current repo, but fetch code from ANOTHER repo!
    - repository: toBeScannedRepo  # TODO: will be scanned
      type: git
      name: 'SV_Security project/code-samples-01'
      trigger:
        branches:
          include:
            - main


# remove it - and it will be triggered by the main branch
trigger: none  # will not be triggered by its own changes!

steps:
  - checkout: toBeScannedRepo
    path: s/scanned  # TODO: notice s/

  - bash: |
      pwd
      ls -al
      # ls -l scanned/
      DOCKER_IMAGE="zricethezav/gitleaks:latest"
      time docker pull ${DOCKER_IMAGE}
      docker images
      # logFile=$(Build.BuildNumber).gitleaks.txt
      # logFile=gitleaks.txt
      docker run ${DOCKER_IMAGE} --help  # to see available options
      touch gitleaks.sarif && chmod 666 gitleaks.sarif  # TODO: needs to exist and be writable from the container!
      ls -al
      # TODO: --exit-code 0 means "not to fail immediately", continue with subsequent commands!
      time docker run -v $(pwd):/path ${DOCKER_IMAGE} detect \
          --source "/path/${scanSubdir}/" --verbose --exit-code 0 \
          --report-format sarif --report-path /path/gitleaks.sarif  # NB: -v $(pwd):/path!
      sleep 1
      ls -al
      sleep 1
      # cat gitleaks.sarif
      head -n 30 gitleaks.sarif
      ls -al ../
      ls -al ../../
    displayName: 'Gitleaks scan'
