# 2023-03-11

# https://github.com/bridgecrewio/checkov-action

name: checkov-03
# on: [push]
on:
  push:
    branches:
      # - main
      - nonexistent  # avoid triggering on main
jobs:
  Checkov-Terraform-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkov Code
        uses: actions/checkout@v3
      - name: Scan with Checkov
        id: checkov  # TODO: what for? For reference, from other jobs or steps
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform-in-action/chapter1
          framework: terraform  # {cloudformation,terraform,kubernetes,all}
          output_format: sarif  # optional: the output format, one of: cli, json, junitxml, github_failed_only, or sarif. Default: sarif
          output_file_path: checkov-results.sarif # folder and name of results file
          soft_fail: true  # do not fail, to upload result in the next step
      - name: Upload Checkov scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'checkov-results.sarif'
          wait-for-processing: "true"
