# 2023-03-13, from ci-...

# This workflow runs static analysis checks on pull requests.
name: ci-static-analysis-aws-enc-02

on:
  # pull_request:
  push:
    branches:
      - main
      # - nonexistent  # avoid triggering on main
  # Run once a day
  # schedule:
  #   - cron: '0 0 * * *'

env:
  SCANNED_REPO: 'scanned-repo'  # constant for multiple reuse

jobs:
  analysis:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        category:
# Disabled pending completion of integration
# https://github.com/aws/aws-dynamodb-encryption-python/issues/66
#          - mypy-py2
#          - mypy-py3
          - bandit
          - doc8
          - readme
          - docs
          - flake8
          - pylint
          - flake8-tests
          - flake8-examples
          - pylint-tests
          - pylint-examples
          - black-check
    steps:
      - name: Checkout from another repo
        uses: actions/checkout@v3
        with:
          repository: 'solita/sv-security-scans-05'
          ref: 'main'
          path: ${{ env.SCANNED_REPO }}  # Relative path under $GITHUB_WORKSPACE to place the repository
      - name: Explore
        run: |
          pwd
          ls -al
          ls -al ${{ env.SCANNED_REPO }}
          exit 1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # fails with '3.11'
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r aws-dynamodb-encryption-python/dev_requirements/ci-requirements.txt
      - name: tox check
        env:
          TOXENV: ${{ matrix.category }}
        run: |
          cd aws-dynamodb-encryption-python
          tox -- -vv
