# 2023-03-11

name: tfsec-02
on:  # [push]
  push:
    branches:
      - main
      # - nonexistent  # avoid triggering on main
jobs:
  TFSec-Terraform-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: TFSec Scan
        # uses: aquasecurity/tfsec-action@master
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          version: latest
          soft_fail: true
          working_directory: terraform-in-action/chapter1
          # TODO: only if it is a public repo or you have GHAS!
          format: sarif  # dumps SARIF to output
          additional_args: '--out foo.sarif'  # to print help use '> foo.sarif'
      - name: Explore Results
        run: |
          set -ux
          pwd
          ls -al
          # cat tfsec
          cat foo.sarif
      # TODO: only if it is a public repo or you have GHAS!
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: foo.sarif
          category: my-TFSec-scan
          wait-for-processing: "true"
