# 2023-03-12

name: trivy-05-image
on:
  push:
    branches:
      # - main
      - nonexistent  # avoid triggering on main
jobs:
  scan:
    name: scan
    runs-on: ubuntu-latest
    env:
      # haveGHAS: 'false'
      haveGHAS: 'true'
      image: 'ubuntu:latest'
    steps:
      # TODO: if you build your own Docker image, run these two steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      # - name: Build an image from Dockerfile
      #   run: |
      #     docker build -t ... .
      # TODO: now scan the image, without GHAS:
      - name: Trivy scanner in image mode, without GHAS
        if: env.haveGHAS == 'false'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: ${{ env.image }}

      # TODO: now scan the image, with GHAS:
      - name: Trivy scanner in image mode, with GHAS
        if: env.haveGHAS == 'true'
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: ${{ env.image }}
          format: 'sarif'
          output: 'trivy-results.sarif'
      # TODO: upload results to GitHub, with GHAS:
      # Error: Advanced Security must be enabled for this repository to use code scanning
      - name: Upload Trivy scan results to GitHub Security tab, with GHAS
        if: env.haveGHAS == 'true'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
